// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab10_ASP.ContextDataBase;

#nullable disable

namespace lab10_ASP.Migrations
{
    [DbContext(typeof(UniversityDbDormanchukContext))]
    partial class UniversityDbDormanchukContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Cyrillic_General_CI_AS")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("lab10_ASP.Tables.Ведомости", b =>
                {
                    b.Property<int>("КодЗаписи")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("код_записи");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("КодЗаписи"));

                    b.Property<DateOnly>("ДатаСдачи")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("дата_сдачи")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Дисциплина")
                        .HasColumnType("int")
                        .HasColumnName("дисциплина");

                    b.Property<int>("Оценка")
                        .HasColumnType("int")
                        .HasColumnName("оценка");

                    b.Property<int>("Преподаватель")
                        .HasColumnType("int")
                        .HasColumnName("преподаватель");

                    b.Property<int>("Студент")
                        .HasColumnType("int")
                        .HasColumnName("студент");

                    b.HasKey("КодЗаписи");

                    b.HasIndex("Дисциплина");

                    b.HasIndex("Преподаватель");

                    b.HasIndex("Студент");

                    b.ToTable("Ведомости", (string)null);
                });

            modelBuilder.Entity("lab10_ASP.Tables.Дисциплины", b =>
                {
                    b.Property<int>("КодДисциплины")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("код_дисциплины");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("КодДисциплины"));

                    b.Property<string>("ВидКонтроля")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("вид_контроля");

                    b.Property<int>("Кафедра")
                        .HasColumnType("int")
                        .HasColumnName("кафедра");

                    b.Property<int>("КолВоЧасов")
                        .HasColumnType("int")
                        .HasColumnName("кол_во_часов");

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("название");

                    b.Property<int>("Преподаватель")
                        .HasColumnType("int")
                        .HasColumnName("преподаватель");

                    b.HasKey("КодДисциплины");

                    b.HasIndex("Кафедра");

                    b.HasIndex("Преподаватель");

                    b.ToTable("Дисциплины", (string)null);
                });

            modelBuilder.Entity("lab10_ASP.Tables.Кафедры", b =>
                {
                    b.Property<int>("КодКафедры")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("код_кафедры");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("КодКафедры"));

                    b.Property<int>("КолВоПреподавателей")
                        .HasColumnType("int")
                        .HasColumnName("кол_во_преподавателей");

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("название");

                    b.Property<int>("НомерКомнаты")
                        .HasColumnType("int")
                        .HasColumnName("номер_комнаты");

                    b.Property<int>("НомерКорпуса")
                        .HasColumnType("int")
                        .HasColumnName("номер_корпуса");

                    b.Property<string>("Телефон")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("телефон");

                    b.Property<string>("Факультет")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("факультет");

                    b.Property<string>("ФиоЗаведующего")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("фио_заведующего");

                    b.HasKey("КодКафедры");

                    b.ToTable("Кафедры", (string)null);
                });

            modelBuilder.Entity("lab10_ASP.Tables.Преподаватели", b =>
                {
                    b.Property<int>("КодПреподавателя")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("код_преподавателя");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("КодПреподавателя"));

                    b.Property<string>("Адрес")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("адрес");

                    b.Property<int>("ГодПоступления")
                        .HasColumnType("int")
                        .HasColumnName("год_поступления");

                    b.Property<int>("ГодРождения")
                        .HasColumnType("int")
                        .HasColumnName("год_рождения");

                    b.Property<string>("Город")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("город");

                    b.Property<string>("Должность")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("должность");

                    b.Property<string>("Имя")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("имя");

                    b.Property<int>("Кафедра")
                        .HasColumnType("int")
                        .HasColumnName("кафедра");

                    b.Property<string>("Отчество")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("отчество");

                    b.Property<string>("Пол")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("пол")
                        .IsFixedLength();

                    b.Property<int>("Стаж")
                        .HasColumnType("int")
                        .HasColumnName("стаж");

                    b.Property<string>("Телефон")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("телефон");

                    b.Property<string>("Фамилия")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("фамилия");

                    b.HasKey("КодПреподавателя");

                    b.HasIndex("Кафедра");

                    b.ToTable("Преподаватели", (string)null);
                });

            modelBuilder.Entity("lab10_ASP.Tables.Студенты", b =>
                {
                    b.Property<int>("КодСтудента")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("код_студента");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("КодСтудента"));

                    b.Property<string>("Адрес")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("адрес");

                    b.Property<int>("ГодРождения")
                        .HasColumnType("int")
                        .HasColumnName("год_рождения");

                    b.Property<string>("Город")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("город");

                    b.Property<string>("Имя")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("имя");

                    b.Property<int>("Кафедра")
                        .HasColumnType("int")
                        .HasColumnName("кафедра");

                    b.Property<string>("Отчество")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("отчество");

                    b.Property<string>("Пол")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("пол")
                        .IsFixedLength();

                    b.Property<string>("Телефон")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("телефон");

                    b.Property<string>("Фамилия")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("фамилия");

                    b.HasKey("КодСтудента");

                    b.HasIndex("Кафедра");

                    b.ToTable("Студенты", (string)null);
                });

            modelBuilder.Entity("lab10_ASP.Tables.Ведомости", b =>
                {
                    b.HasOne("lab10_ASP.Tables.Дисциплины", "ДисциплинаNavigation")
                        .WithMany("Ведомостиs")
                        .HasForeignKey("Дисциплина")
                        .IsRequired()
                        .HasConstraintName("FK_Ведомости_Дисциплины");

                    b.HasOne("lab10_ASP.Tables.Преподаватели", "ПреподавательNavigation")
                        .WithMany("Ведомостиs")
                        .HasForeignKey("Преподаватель")
                        .IsRequired()
                        .HasConstraintName("FK_Ведомости_Преподаватели");

                    b.HasOne("lab10_ASP.Tables.Студенты", "СтудентNavigation")
                        .WithMany("Ведомостиs")
                        .HasForeignKey("Студент")
                        .IsRequired()
                        .HasConstraintName("FK_Ведомости_Студенты");

                    b.Navigation("ДисциплинаNavigation");

                    b.Navigation("ПреподавательNavigation");

                    b.Navigation("СтудентNavigation");
                });

            modelBuilder.Entity("lab10_ASP.Tables.Дисциплины", b =>
                {
                    b.HasOne("lab10_ASP.Tables.Кафедры", "КафедраNavigation")
                        .WithMany("Дисциплиныs")
                        .HasForeignKey("Кафедра")
                        .IsRequired()
                        .HasConstraintName("FK_Дисциплины_Кафедры");

                    b.HasOne("lab10_ASP.Tables.Преподаватели", "ПреподавательNavigation")
                        .WithMany("Дисциплиныs")
                        .HasForeignKey("Преподаватель")
                        .IsRequired()
                        .HasConstraintName("FK_Дисциплины_Преподаватели");

                    b.Navigation("КафедраNavigation");

                    b.Navigation("ПреподавательNavigation");
                });

            modelBuilder.Entity("lab10_ASP.Tables.Преподаватели", b =>
                {
                    b.HasOne("lab10_ASP.Tables.Кафедры", "КафедраNavigation")
                        .WithMany("Преподавателиs")
                        .HasForeignKey("Кафедра")
                        .IsRequired()
                        .HasConstraintName("FK_Преподаватели_Кафедры");

                    b.Navigation("КафедраNavigation");
                });

            modelBuilder.Entity("lab10_ASP.Tables.Студенты", b =>
                {
                    b.HasOne("lab10_ASP.Tables.Кафедры", "КафедраNavigation")
                        .WithMany("Студентыs")
                        .HasForeignKey("Кафедра")
                        .IsRequired()
                        .HasConstraintName("FK_Студенты_Кафедры");

                    b.Navigation("КафедраNavigation");
                });

            modelBuilder.Entity("lab10_ASP.Tables.Дисциплины", b =>
                {
                    b.Navigation("Ведомостиs");
                });

            modelBuilder.Entity("lab10_ASP.Tables.Кафедры", b =>
                {
                    b.Navigation("Дисциплиныs");

                    b.Navigation("Преподавателиs");

                    b.Navigation("Студентыs");
                });

            modelBuilder.Entity("lab10_ASP.Tables.Преподаватели", b =>
                {
                    b.Navigation("Ведомостиs");

                    b.Navigation("Дисциплиныs");
                });

            modelBuilder.Entity("lab10_ASP.Tables.Студенты", b =>
                {
                    b.Navigation("Ведомостиs");
                });
#pragma warning restore 612, 618
        }
    }
}
